# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-16 01:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of this career', max_length=250)),
                ('description', models.CharField(help_text='Description of this career', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of Faculty', max_length=250)),
                ('description', models.CharField(help_text='Description of Faculty', max_length=500)),
                ('application_info', models.CharField(max_length=1250)),
            ],
        ),
        migrations.CreateModel(
            name='FacultyTuition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_category', models.CharField(help_text='Student category concerned by this tuition (e.g. foreign student, in-state student)', max_length=250)),
                ('period', models.CharField(help_text='Period for tuition payment (e.g. year, semester)', max_length=25)),
                ('payments', models.CharField(help_text='List of payments asked each period. (separator: ";")', max_length=999)),
                ('total', models.IntegerField(blank=True, default=0, help_text='Total amount to pay for tuition for the length of an entire program.')),
                ('faculty', models.ForeignKey(help_text='university faculty linked to this tuition.', on_delete=django.db.models.deletion.CASCADE, related_name='tuitions', to='colleges.Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='FieldCareer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career', models.ForeignKey(help_text='Career linked with field of study.', on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='colleges.Career')),
            ],
        ),
        migrations.CreateModel(
            name='FieldProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramTuition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_category', models.CharField(help_text='Student category concerned by this tuition (e.g. foreign student, in-state student)', max_length=250)),
                ('period', models.CharField(help_text='Period for tuition payment (e.g. year, semester)', max_length=25)),
                ('payments', models.CharField(help_text='List of payments asked each period. (separator: ";")', max_length=999)),
                ('total', models.IntegerField(help_text='Total amount to pay for tuition for the entire program.')),
            ],
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conditions', models.CharField(help_text='List of conditions for this scholarship. (separator: ";")', max_length=999)),
                ('amount', models.IntegerField(help_text='Amount of money in this scholarship.')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of Institution', max_length=250)),
                ('type', models.IntegerField(choices=[(1, 'university'), (2, 'other')], help_text='Type of institution.')),
                ('location', models.IntegerField(choices=[(1, 'Lusaka'), (2, 'Ndola'), (3, 'Choma'), (4, 'Chipata')], help_text='State location of this school.')),
                ('ownership', models.IntegerField(choices=[(1, 'private'), (2, 'public')], help_text='Is it a private school or a public school ?')),
            ],
        ),
        migrations.CreateModel(
            name='StudyField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of this field of study.', max_length=250)),
                ('description', models.CharField(help_text='Description of this field of study.', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='StudyProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of this program.', max_length=250)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('level', models.IntegerField(choices=[(1, 'undergraduate'), (2, 'graduate')], help_text='Level of current program.')),
                ('length', models.IntegerField(help_text='Length of this study program in the selected base unit.')),
                ('base_time_unit', models.IntegerField(choices=[(1, 'semester(s)'), (2, 'year(s)')])),
                ('faculty', models.ForeignKey(help_text='Faculty with this program.', on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='colleges.Faculty')),
            ],
        ),
        migrations.AddField(
            model_name='programtuition',
            name='program',
            field=models.ForeignKey(help_text='university program linked to this tuition.', on_delete=django.db.models.deletion.CASCADE, related_name='tuitions', to='colleges.StudyProgram'),
        ),
        migrations.AddField(
            model_name='fieldprogram',
            name='field',
            field=models.ForeignKey(help_text='Field of study linked with program.', on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='colleges.StudyField'),
        ),
        migrations.AddField(
            model_name='fieldprogram',
            name='program',
            field=models.ForeignKey(help_text='Program linked with field of study.', on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='colleges.StudyProgram'),
        ),
        migrations.AddField(
            model_name='fieldcareer',
            name='field',
            field=models.ForeignKey(help_text='Field of study linked with progra2m.', on_delete=django.db.models.deletion.CASCADE, related_name='careers', to='colleges.StudyField'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculties', to='colleges.School'),
        ),
    ]
