# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-01 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0002_full_search_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyprogram',
            name='admission_requirements',
            field=models.CharField(default='', max_length=9999),
        ),
    ]
