# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-01 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0003_studyprogram_admission_requirements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyprogram',
            name='admission_requirements',
            field=models.CharField(blank=True, default='', max_length=9999),
        ),
    ]
