# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-01 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0004_auto_20170601_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programtuition',
            name='total',
            field=models.IntegerField(blank=True, help_text='Total amount to pay for tuition for the program.', null=True),
        ),
    ]
